name: Next.js Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: 20.48.90.191
        username: MBCcoin
        password: tradingCoin123
        port: 22
        script: |
          kill $(lsof -t -i:3000)
          cd /home/coinns 
          git pull origin main 
          yarn install 
          yarn build 
          yarn start

